# Generated by Django 3.1.2 on 2020-10-18 06:55

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='Bakery Owner'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 6, 55, 32, 741587)),
        ),
    ]
