# Generated by Django 3.1.2 on 2020-10-18 13:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20201018_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 13, 1, 31, 729892)),
        ),
    ]
